<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>XPath</name>
   <tag></tag>
   <elementGuidId>e178fb96-0ab2-417b-bf97-dbbb3c89faf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${a}</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${a}</value>
   </webElementProperties>
</WebElementEntity>
